sonar.projectKey=emertrack
sonar.projectName=Emertrack Backend
sonar.language=go

# Only measure coverage on service layer, not repo/handler
sonar.coverage.exclusions=**/repository.go,**/handler.go,**/mocks/**,**/dto/**,**/domain/**,**/router/**,**/middleware/**,**/cmd/**,**/migrations/**

# Point to coverage report
sonar.go.coverage.reportPaths=coverage.out