// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ApprovalService is an autogenerated mock type for the ApprovalService type
type ApprovalService struct {
	mock.Mock
}

// Approve provides a mock function with given fields: ctx, reviewerID, approvalID, notes
func (_m *ApprovalService) Approve(ctx context.Context, reviewerID uint, approvalID uint, notes string) (string, error) {
	ret := _m.Called(ctx, reviewerID, approvalID, notes)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (string, error)); ok {
		return rf(ctx, reviewerID, approvalID, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) string); ok {
		r0 = rf(ctx, reviewerID, approvalID, notes)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, reviewerID, approvalID, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApprovalDetail provides a mock function with given fields: ctx, id
func (_m *ApprovalService) GetApprovalDetail(ctx context.Context, id uint) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovalDetail")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListApprovals provides a mock function with given fields: ctx, filter
func (_m *ApprovalService) ListApprovals(ctx context.Context, filter domain.ApprovalFilter) ([]domain.ApprovalResponse, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListApprovals")
	}

	var r0 []domain.ApprovalResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApprovalFilter) ([]domain.ApprovalResponse, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApprovalFilter) []domain.ApprovalResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ApprovalFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ApprovalFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Reject provides a mock function with given fields: ctx, reviewerID, approvalID, notes
func (_m *ApprovalService) Reject(ctx context.Context, reviewerID uint, approvalID uint, notes string) (string, error) {
	ret := _m.Called(ctx, reviewerID, approvalID, notes)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (string, error)); ok {
		return rf(ctx, reviewerID, approvalID, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) string); ok {
		r0 = rf(ctx, reviewerID, approvalID, notes)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, reviewerID, approvalID, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApprovalService creates a new instance of ApprovalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApprovalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApprovalService {
	mock := &ApprovalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
