// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// ApprovalRepository is an autogenerated mock type for the ApprovalRepository type
type ApprovalRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *ApprovalRepository) Create(ctx context.Context, req *domain.ApprovalRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ApprovalRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTx provides a mock function with given fields: ctx, tx, req
func (_m *ApprovalRepository) CreateTx(ctx context.Context, tx *gorm.DB, req *domain.ApprovalRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *domain.ApprovalRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ApprovalRepository) FindByID(ctx context.Context, id uint) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *ApprovalRepository) List(ctx context.Context, filter domain.ApprovalFilter) ([]domain.ApprovalResponse, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.ApprovalResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApprovalFilter) ([]domain.ApprovalResponse, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApprovalFilter) []domain.ApprovalResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ApprovalFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ApprovalFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, req
func (_m *ApprovalRepository) Update(ctx context.Context, req *domain.ApprovalRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ApprovalRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTx provides a mock function with given fields: tx, req
func (_m *ApprovalRepository) UpdateTx(tx *gorm.DB, req *domain.ApprovalRequest) error {
	ret := _m.Called(tx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *domain.ApprovalRequest) error); ok {
		r0 = rf(tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApprovalRepository creates a new instance of ApprovalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApprovalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApprovalRepository {
	mock := &ApprovalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
