// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "emertrack/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// AuditService is an autogenerated mock type for the AuditService type
type AuditService struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, menu, entityID, page, pageSize
func (_m *AuditService) List(ctx context.Context, menu string, entityID *uint, page int, pageSize int) (*dto.PaginatedResponse, error) {
	ret := _m.Called(ctx, menu, entityID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.PaginatedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint, int, int) (*dto.PaginatedResponse, error)); ok {
		return rf(ctx, menu, entityID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint, int, int) *dto.PaginatedResponse); ok {
		r0 = rf(ctx, menu, entityID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PaginatedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uint, int, int) error); ok {
		r1 = rf(ctx, menu, entityID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Log provides a mock function with given fields: ctx, userID, action, menu, desc, entityID
func (_m *AuditService) Log(ctx context.Context, userID uint, action string, menu string, desc string, entityID *uint) error {
	ret := _m.Called(ctx, userID, action, menu, desc, entityID)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, *uint) error); ok {
		r0 = rf(ctx, userID, action, menu, desc, entityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditService creates a new instance of AuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditService {
	mock := &AuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
