// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"
	dto "emertrack/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// AuditRepository is an autogenerated mock type for the AuditRepository type
type AuditRepository struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, menu, entityID, page, pageSize
func (_m *AuditRepository) List(ctx context.Context, menu string, entityID *uint, page int, pageSize int) ([]dto.AuditResponse, int64, error) {
	ret := _m.Called(ctx, menu, entityID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.AuditResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint, int, int) ([]dto.AuditResponse, int64, error)); ok {
		return rf(ctx, menu, entityID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint, int, int) []dto.AuditResponse); ok {
		r0 = rf(ctx, menu, entityID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AuditResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uint, int, int) int64); ok {
		r1 = rf(ctx, menu, entityID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *uint, int, int) error); ok {
		r2 = rf(ctx, menu, entityID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Log provides a mock function with given fields: ctx, log
func (_m *AuditRepository) Log(ctx context.Context, log *domain.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditRepository creates a new instance of AuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditRepository {
	mock := &AuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
