// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// DashboardService is an autogenerated mock type for the DashboardService type
type DashboardService struct {
	mock.Mock
}

// GetDashboardData provides a mock function with given fields: ctx, filter
func (_m *DashboardService) GetDashboardData(ctx context.Context, filter domain.TableFilter) (domain.DashboardSummary, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardData")
	}

	var r0 domain.DashboardSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TableFilter) (domain.DashboardSummary, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TableFilter) domain.DashboardSummary); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(domain.DashboardSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TableFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDashboardTable provides a mock function with given fields: ctx, filter
func (_m *DashboardService) ListDashboardTable(ctx context.Context, filter domain.TableFilter) ([]domain.DashboardTableRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListDashboardTable")
	}

	var r0 []domain.DashboardTableRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TableFilter) ([]domain.DashboardTableRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TableFilter) []domain.DashboardTableRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DashboardTableRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TableFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.TableFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewDashboardService creates a new instance of DashboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardService {
	mock := &DashboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
