// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// InspectionRepository is an autogenerated mock type for the InspectionRepository type
type InspectionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, insp
func (_m *InspectionRepository) Create(ctx context.Context, insp *domain.Inspection) error {
	ret := _m.Called(ctx, insp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Inspection) error); ok {
		r0 = rf(ctx, insp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateItem provides a mock function with given fields: ctx, item
func (_m *InspectionRepository) CreateItem(ctx context.Context, item *domain.InspectionItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.InspectionItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSchedule provides a mock function with given fields: ctx, schedule
func (_m *InspectionRepository) CreateSchedule(ctx context.Context, schedule *domain.InspectionSchedule) error {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.InspectionSchedule) error); ok {
		r0 = rf(ctx, schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *InspectionRepository) FindByID(ctx context.Context, id uint) (*domain.Inspection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Inspection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Inspection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Inspection); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inspection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestBySarpras provides a mock function with given fields: ctx, sarprasID
func (_m *InspectionRepository) GetLatestBySarpras(ctx context.Context, sarprasID uint) (*domain.Inspection, error) {
	ret := _m.Called(ctx, sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBySarpras")
	}

	var r0 *domain.Inspection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Inspection, error)); ok {
		return rf(ctx, sarprasID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Inspection); ok {
		r0 = rf(ctx, sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Inspection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRepairOrderByInspection provides a mock function with given fields: ctx, inspectionID
func (_m *InspectionRepository) GetRepairOrderByInspection(ctx context.Context, inspectionID uint) (*domain.RepairOrder, error) {
	ret := _m.Called(ctx, inspectionID)

	if len(ret) == 0 {
		panic("no return value specified for GetRepairOrderByInspection")
	}

	var r0 *domain.RepairOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.RepairOrder, error)); ok {
		return rf(ctx, inspectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.RepairOrder); ok {
		r0 = rf(ctx, inspectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RepairOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, inspectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewBySubmission provides a mock function with given fields: ctx, submissionID
func (_m *InspectionRepository) GetReviewBySubmission(ctx context.Context, submissionID uint) (*domain.ReviewOrder, error) {
	ret := _m.Called(ctx, submissionID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewBySubmission")
	}

	var r0 *domain.ReviewOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.ReviewOrder, error)); ok {
		return rf(ctx, submissionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.ReviewOrder); ok {
		r0 = rf(ctx, submissionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReviewOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, submissionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewerByID provides a mock function with given fields: ctx, reviewerID
func (_m *InspectionRepository) GetReviewerByID(ctx context.Context, reviewerID uint) (*domain.User, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewerByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.User, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.User); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSarprasForScheduling provides a mock function with given fields: ctx
func (_m *InspectionRepository) GetSarprasForScheduling(ctx context.Context) ([]domain.SarprasSchedulingData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSarprasForScheduling")
	}

	var r0 []domain.SarprasSchedulingData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SarprasSchedulingData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SarprasSchedulingData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasSchedulingData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSchedulesForReminder provides a mock function with given fields: ctx
func (_m *InspectionRepository) GetSchedulesForReminder(ctx context.Context) ([]domain.InspectionSchedule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSchedulesForReminder")
	}

	var r0 []domain.InspectionSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.InspectionSchedule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.InspectionSchedule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubmissionsByRepairOrder provides a mock function with given fields: ctx, repairOrderID
func (_m *InspectionRepository) GetSubmissionsByRepairOrder(ctx context.Context, repairOrderID uint) ([]domain.RepairSubmission, error) {
	ret := _m.Called(ctx, repairOrderID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubmissionsByRepairOrder")
	}

	var r0 []domain.RepairSubmission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.RepairSubmission, error)); ok {
		return rf(ctx, repairOrderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.RepairSubmission); ok {
		r0 = rf(ctx, repairOrderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RepairSubmission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, repairOrderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasActiveSchedule provides a mock function with given fields: ctx, sarprasID
func (_m *InspectionRepository) HasActiveSchedule(ctx context.Context, sarprasID uint) (bool, error) {
	ret := _m.Called(ctx, sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveSchedule")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, sarprasID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, sarprasID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasScheduleForDueDate provides a mock function with given fields: ctx, sarprasID, dueDate
func (_m *InspectionRepository) HasScheduleForDueDate(ctx context.Context, sarprasID uint, dueDate time.Time) (bool, error) {
	ret := _m.Called(ctx, sarprasID, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for HasScheduleForDueDate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) (bool, error)); ok {
		return rf(ctx, sarprasID, dueDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) bool); ok {
		r0 = rf(ctx, sarprasID, dueDate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, time.Time) error); ok {
		r1 = rf(ctx, sarprasID, dueDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActiveTasks provides a mock function with given fields: ctx, filter
func (_m *InspectionRepository) ListActiveTasks(ctx context.Context, filter domain.InspectionFilter) ([]domain.InspectionRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveTasks")
	}

	var r0 []domain.InspectionRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionFilter) ([]domain.InspectionRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionFilter) []domain.InspectionRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InspectionFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.InspectionFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListHistory provides a mock function with given fields: ctx, filter
func (_m *InspectionRepository) ListHistory(ctx context.Context, filter domain.InspectionHistoryFilter) ([]domain.InspectionHistoryRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListHistory")
	}

	var r0 []domain.InspectionHistoryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionHistoryFilter) ([]domain.InspectionHistoryRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionHistoryFilter) []domain.InspectionHistoryRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionHistoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InspectionHistoryFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.InspectionHistoryFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListMonitoring provides a mock function with given fields: ctx, filter
func (_m *InspectionRepository) ListMonitoring(ctx context.Context, filter domain.InspectionMonitoringFilter) ([]domain.InspectionMonitoringRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListMonitoring")
	}

	var r0 []domain.InspectionMonitoringRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionMonitoringFilter) ([]domain.InspectionMonitoringRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionMonitoringFilter) []domain.InspectionMonitoringRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionMonitoringRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InspectionMonitoringFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.InspectionMonitoringFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateMarkAsNotReady provides a mock function with given fields: ctx
func (_m *InspectionRepository) UpdateMarkAsNotReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMarkAsNotReady")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOverdueSchedules provides a mock function with given fields: ctx
func (_m *InspectionRepository) UpdateOverdueSchedules(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOverdueSchedules")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInspectionRepository creates a new instance of InspectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInspectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InspectionRepository {
	mock := &InspectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
