// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// InspectionService is an autogenerated mock type for the InspectionService type
type InspectionService struct {
	mock.Mock
}

// CancelClaim provides a mock function with given fields: ctx, scheduleID, userID
func (_m *InspectionService) CancelClaim(ctx context.Context, scheduleID uint, userID uint) error {
	ret := _m.Called(ctx, scheduleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelClaim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, scheduleID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimInspection provides a mock function with given fields: ctx, scheduleID, userID
func (_m *InspectionService) ClaimInspection(ctx context.Context, scheduleID uint, userID uint) error {
	ret := _m.Called(ctx, scheduleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimInspection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, scheduleID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateSchedulesDueSoon provides a mock function with given fields: ctx
func (_m *InspectionService) GenerateSchedulesDueSoon(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSchedulesDueSoon")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInspectionDetail provides a mock function with given fields: ctx, id
func (_m *InspectionService) GetInspectionDetail(ctx context.Context, id uint) (*domain.InspectionDetailResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInspectionDetail")
	}

	var r0 *domain.InspectionDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.InspectionDetailResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.InspectionDetailResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InspectionDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInspectionForm provides a mock function with given fields: ctx, sarprasID
func (_m *InspectionService) GetInspectionForm(ctx context.Context, sarprasID uint) (*domain.InspectionFormResponse, error) {
	ret := _m.Called(ctx, sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetInspectionForm")
	}

	var r0 *domain.InspectionFormResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.InspectionFormResponse, error)); ok {
		return rf(ctx, sarprasID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.InspectionFormResponse); ok {
		r0 = rf(ctx, sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InspectionFormResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActiveTasks provides a mock function with given fields: ctx, filter
func (_m *InspectionService) ListActiveTasks(ctx context.Context, filter domain.InspectionFilter) ([]domain.InspectionRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveTasks")
	}

	var r0 []domain.InspectionRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionFilter) ([]domain.InspectionRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionFilter) []domain.InspectionRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InspectionFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.InspectionFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListHistory provides a mock function with given fields: ctx, filter
func (_m *InspectionService) ListHistory(ctx context.Context, filter domain.InspectionHistoryFilter) ([]domain.InspectionHistoryRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListHistory")
	}

	var r0 []domain.InspectionHistoryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionHistoryFilter) ([]domain.InspectionHistoryRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionHistoryFilter) []domain.InspectionHistoryRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionHistoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InspectionHistoryFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.InspectionHistoryFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListMonitoring provides a mock function with given fields: ctx, filter
func (_m *InspectionService) ListMonitoring(ctx context.Context, filter domain.InspectionMonitoringFilter) ([]domain.InspectionMonitoringRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListMonitoring")
	}

	var r0 []domain.InspectionMonitoringRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionMonitoringFilter) ([]domain.InspectionMonitoringRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InspectionMonitoringFilter) []domain.InspectionMonitoringRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InspectionMonitoringRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InspectionMonitoringFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.InspectionMonitoringFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendInspectionReminders provides a mock function with given fields: ctx
func (_m *InspectionService) SendInspectionReminders(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SendInspectionReminders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitInspection provides a mock function with given fields: ctx, req, checkerID
func (_m *InspectionService) SubmitInspection(ctx context.Context, req *domain.SubmitInspectionRequest, checkerID uint) (*domain.InspectionSubmitResult, error) {
	ret := _m.Called(ctx, req, checkerID)

	if len(ret) == 0 {
		panic("no return value specified for SubmitInspection")
	}

	var r0 *domain.InspectionSubmitResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SubmitInspectionRequest, uint) (*domain.InspectionSubmitResult, error)); ok {
		return rf(ctx, req, checkerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SubmitInspectionRequest, uint) *domain.InspectionSubmitResult); ok {
		r0 = rf(ctx, req, checkerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InspectionSubmitResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.SubmitInspectionRequest, uint) error); ok {
		r1 = rf(ctx, req, checkerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMarkAsNotReady provides a mock function with given fields: ctx
func (_m *InspectionService) UpdateMarkAsNotReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMarkAsNotReady")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOverdueAndNotReady provides a mock function with given fields: ctx
func (_m *InspectionService) UpdateOverdueAndNotReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOverdueAndNotReady")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOverdueSchedules provides a mock function with given fields: ctx
func (_m *InspectionService) UpdateOverdueSchedules(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOverdueSchedules")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInspectionService creates a new instance of InspectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInspectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InspectionService {
	mock := &InspectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
