// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MasterService is an autogenerated mock type for the MasterService type
type MasterService struct {
	mock.Mock
}

// ListDepartments provides a mock function with given fields: ctx, filter
func (_m *MasterService) ListDepartments(ctx context.Context, filter map[string]interface{}) ([]domain.DepartmentRow, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListDepartments")
	}

	var r0 []domain.DepartmentRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]domain.DepartmentRow, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []domain.DepartmentRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DepartmentRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSites provides a mock function with given fields: ctx, filter
func (_m *MasterService) ListSites(ctx context.Context, filter map[string]interface{}) ([]domain.Site, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSites")
	}

	var r0 []domain.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]domain.Site, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []domain.Site); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestCreateDepartment provides a mock function with given fields: ctx, userID, req
func (_m *MasterService) RequestCreateDepartment(ctx context.Context, userID uint, req *domain.Department) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestCreateDepartment")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Department) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Department) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *domain.Department) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestCreateSite provides a mock function with given fields: ctx, userID, req
func (_m *MasterService) RequestCreateSite(ctx context.Context, userID uint, req *domain.Site) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestCreateSite")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Site) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Site) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *domain.Site) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestDeleteDepartment provides a mock function with given fields: ctx, userID, id
func (_m *MasterService) RequestDeleteDepartment(ctx context.Context, userID uint, id uint) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeleteDepartment")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestDeleteSite provides a mock function with given fields: ctx, userID, id
func (_m *MasterService) RequestDeleteSite(ctx context.Context, userID uint, id uint) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeleteSite")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestEditDepartment provides a mock function with given fields: ctx, userID, id, req
func (_m *MasterService) RequestEditDepartment(ctx context.Context, userID uint, id uint, req *domain.Department) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestEditDepartment")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.Department) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.Department) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *domain.Department) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestEditSite provides a mock function with given fields: ctx, userID, id, req
func (_m *MasterService) RequestEditSite(ctx context.Context, userID uint, id uint, req *domain.Site) (*domain.ApprovalRequest, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for RequestEditSite")
	}

	var r0 *domain.ApprovalRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.Site) (*domain.ApprovalRequest, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.Site) *domain.ApprovalRequest); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *domain.Site) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMasterService creates a new instance of MasterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMasterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MasterService {
	mock := &MasterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
