// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MasterRepository is an autogenerated mock type for the MasterRepository type
type MasterRepository struct {
	mock.Mock
}

// CheckDepartmentReferences provides a mock function with given fields: ctx, id
func (_m *MasterRepository) CheckDepartmentReferences(ctx context.Context, id uint) (*domain.DepartmentReferences, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckDepartmentReferences")
	}

	var r0 *domain.DepartmentReferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.DepartmentReferences, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.DepartmentReferences); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DepartmentReferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckSiteReferences provides a mock function with given fields: ctx, id
func (_m *MasterRepository) CheckSiteReferences(ctx context.Context, id uint) (*domain.SiteReferences, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckSiteReferences")
	}

	var r0 *domain.SiteReferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.SiteReferences, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.SiteReferences); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SiteReferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDepartment provides a mock function with given fields: ctx, d
func (_m *MasterRepository) CreateDepartment(ctx context.Context, d *domain.Department) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for CreateDepartment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Department) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateGenericTx provides a mock function with given fields: tx, entity
func (_m *MasterRepository) CreateGenericTx(tx *gorm.DB, entity interface{}) error {
	ret := _m.Called(tx, entity)

	if len(ret) == 0 {
		panic("no return value specified for CreateGenericTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, interface{}) error); ok {
		r0 = rf(tx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSite provides a mock function with given fields: ctx, s
func (_m *MasterRepository) CreateSite(ctx context.Context, s *domain.Site) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Site) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDepartment provides a mock function with given fields: ctx, id
func (_m *MasterRepository) DeleteDepartment(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDepartment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteGenericTx provides a mock function with given fields: tx, entity, id
func (_m *MasterRepository) DeleteGenericTx(tx *gorm.DB, entity interface{}, id uint) error {
	ret := _m.Called(tx, entity, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGenericTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, interface{}, uint) error); ok {
		r0 = rf(tx, entity, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSite provides a mock function with given fields: ctx, id
func (_m *MasterRepository) DeleteSite(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCodeDepartment provides a mock function with given fields: ctx, code
func (_m *MasterRepository) FindByCodeDepartment(ctx context.Context, code string) (*domain.Department, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCodeDepartment")
	}

	var r0 *domain.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Department, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Department); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCodeSite provides a mock function with given fields: ctx, code
func (_m *MasterRepository) FindByCodeSite(ctx context.Context, code string) (*domain.Site, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCodeSite")
	}

	var r0 *domain.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Site, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Site); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdDepartment provides a mock function with given fields: ctx, id
func (_m *MasterRepository) FindByIdDepartment(ctx context.Context, id uint) (*domain.Department, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdDepartment")
	}

	var r0 *domain.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Department, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Department); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdSite provides a mock function with given fields: ctx, id
func (_m *MasterRepository) FindByIdSite(ctx context.Context, id uint) (*domain.Site, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdSite")
	}

	var r0 *domain.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Site, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Site); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDepartment provides a mock function with given fields: ctx, filter
func (_m *MasterRepository) ListDepartment(ctx context.Context, filter map[string]interface{}) ([]domain.DepartmentRow, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListDepartment")
	}

	var r0 []domain.DepartmentRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]domain.DepartmentRow, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []domain.DepartmentRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DepartmentRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSite provides a mock function with given fields: ctx, filter
func (_m *MasterRepository) ListSite(ctx context.Context, filter map[string]interface{}) ([]domain.Site, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSite")
	}

	var r0 []domain.Site
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]domain.Site, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []domain.Site); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Site)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDepartment provides a mock function with given fields: ctx, d
func (_m *MasterRepository) UpdateDepartment(ctx context.Context, d *domain.Department) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDepartment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Department) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGenericTx provides a mock function with given fields: tx, id, entity
func (_m *MasterRepository) UpdateGenericTx(tx *gorm.DB, id uint, entity interface{}) error {
	ret := _m.Called(tx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGenericTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, interface{}) error); ok {
		r0 = rf(tx, id, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSite provides a mock function with given fields: ctx, s
func (_m *MasterRepository) UpdateSite(ctx context.Context, s *domain.Site) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Site) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMasterRepository creates a new instance of MasterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMasterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MasterRepository {
	mock := &MasterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
