// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MyTaskRepository is an autogenerated mock type for the MyTaskRepository type
type MyTaskRepository struct {
	mock.Mock
}

// GetMyTasks provides a mock function with given fields: ctx, userID, roles, isSupervisor, isGA
func (_m *MyTaskRepository) GetMyTasks(ctx context.Context, userID uint, roles []string, isSupervisor bool, isGA bool) (*domain.MyTasksResponse, error) {
	ret := _m.Called(ctx, userID, roles, isSupervisor, isGA)

	if len(ret) == 0 {
		panic("no return value specified for GetMyTasks")
	}

	var r0 *domain.MyTasksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []string, bool, bool) (*domain.MyTasksResponse, error)); ok {
		return rf(ctx, userID, roles, isSupervisor, isGA)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, []string, bool, bool) *domain.MyTasksResponse); ok {
		r0 = rf(ctx, userID, roles, isSupervisor, isGA)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MyTasksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, []string, bool, bool) error); ok {
		r1 = rf(ctx, userID, roles, isSupervisor, isGA)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMyTaskRepository creates a new instance of MyTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMyTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MyTaskRepository {
	mock := &MyTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
