// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// DeleteAllNotifications provides a mock function with given fields: ctx, userID
func (_m *NotificationService) DeleteAllNotifications(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteNotification provides a mock function with given fields: ctx, id, userID
func (_m *NotificationService) DeleteNotification(ctx context.Context, id uint, userID uint) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserNotifications provides a mock function with given fields: ctx, userID
func (_m *NotificationService) GetUserNotifications(ctx context.Context, userID uint) ([]domain.Notification, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserNotifications")
	}

	var r0 []domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Notification, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Notification); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAllAsRead provides a mock function with given fields: ctx, userID
func (_m *NotificationService) MarkAllAsRead(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsRead provides a mock function with given fields: ctx, id, userID
func (_m *NotificationService) MarkAsRead(ctx context.Context, id uint, userID uint) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyAPARMarksUsed provides a mock function with given fields: ctx, sarprasIDs, markedBy, reason
func (_m *NotificationService) NotifyAPARMarksUsed(ctx context.Context, sarprasIDs []uint, markedBy uint, reason string) error {
	ret := _m.Called(ctx, sarprasIDs, markedBy, reason)

	if len(ret) == 0 {
		panic("no return value specified for NotifyAPARMarksUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, uint, string) error); ok {
		r0 = rf(ctx, sarprasIDs, markedBy, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyApprovers provides a mock function with given fields: ctx, requesterID, entityType, action, identifier, notes, referenceID
func (_m *NotificationService) NotifyApprovers(ctx context.Context, requesterID uint, entityType string, action string, identifier string, notes string, referenceID uint) error {
	ret := _m.Called(ctx, requesterID, entityType, action, identifier, notes, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyApprovers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, string, uint) error); ok {
		r0 = rf(ctx, requesterID, entityType, action, identifier, notes, referenceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyApproversForBulk provides a mock function with given fields: ctx, requesterID, itemCount, notes, referenceID
func (_m *NotificationService) NotifyApproversForBulk(ctx context.Context, requesterID uint, itemCount int, notes string, referenceID uint) error {
	ret := _m.Called(ctx, requesterID, itemCount, notes, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyApproversForBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, string, uint) error); ok {
		r0 = rf(ctx, requesterID, itemCount, notes, referenceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyNewInspection provides a mock function with given fields: ctx, scheduleID, sarprasCode, sarprasName, deptID, typeID
func (_m *NotificationService) NotifyNewInspection(ctx context.Context, scheduleID uint, sarprasCode string, sarprasName string, deptID uint, typeID uint) error {
	ret := _m.Called(ctx, scheduleID, sarprasCode, sarprasName, deptID, typeID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyNewInspection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, uint, uint) error); ok {
		r0 = rf(ctx, scheduleID, sarprasCode, sarprasName, deptID, typeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyRefillEvidenceSubmitted provides a mock function with given fields: ctx, itemID, evidenceBy, sarprasCode
func (_m *NotificationService) NotifyRefillEvidenceSubmitted(ctx context.Context, itemID uint, evidenceBy uint, sarprasCode string) error {
	ret := _m.Called(ctx, itemID, evidenceBy, sarprasCode)

	if len(ret) == 0 {
		panic("no return value specified for NotifyRefillEvidenceSubmitted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) error); ok {
		r0 = rf(ctx, itemID, evidenceBy, sarprasCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyRefillReviewResult provides a mock function with given fields: ctx, itemID, gaID, status, rejectReason, sarprasCode
func (_m *NotificationService) NotifyRefillReviewResult(ctx context.Context, itemID uint, gaID uint, status string, rejectReason string, sarprasCode string) error {
	ret := _m.Called(ctx, itemID, gaID, status, rejectReason, sarprasCode)

	if len(ret) == 0 {
		panic("no return value specified for NotifyRefillReviewResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, string, string) error); ok {
		r0 = rf(ctx, itemID, gaID, status, rejectReason, sarprasCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyRepairPIC provides a mock function with given fields: ctx, repairID, sarprasCode, sarprasName, picID, notes
func (_m *NotificationService) NotifyRepairPIC(ctx context.Context, repairID uint, sarprasCode string, sarprasName string, picID uint, notes string) error {
	ret := _m.Called(ctx, repairID, sarprasCode, sarprasName, picID, notes)

	if len(ret) == 0 {
		panic("no return value specified for NotifyRepairPIC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, uint, string) error); ok {
		r0 = rf(ctx, repairID, sarprasCode, sarprasName, picID, notes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyRequesterApprovalResult provides a mock function with given fields: ctx, res
func (_m *NotificationService) NotifyRequesterApprovalResult(ctx context.Context, res domain.ApprovalResultNotif) error {
	ret := _m.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for NotifyRequesterApprovalResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApprovalResultNotif) error); ok {
		r0 = rf(ctx, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyReviewer provides a mock function with given fields: ctx, repairOrderID, sarprasCode, sarprasName, picName, notes
func (_m *NotificationService) NotifyReviewer(ctx context.Context, repairOrderID uint, sarprasCode string, sarprasName string, picName string, notes string) error {
	ret := _m.Called(ctx, repairOrderID, sarprasCode, sarprasName, picName, notes)

	if len(ret) == 0 {
		panic("no return value specified for NotifyReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, string) error); ok {
		r0 = rf(ctx, repairOrderID, sarprasCode, sarprasName, picName, notes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendInspectionReminder provides a mock function with given fields: ctx, userID, scheduleID, sarprasCode, daysDiff, isOverdue
func (_m *NotificationService) SendInspectionReminder(ctx context.Context, userID uint, scheduleID uint, sarprasCode string, daysDiff int, isOverdue bool) error {
	ret := _m.Called(ctx, userID, scheduleID, sarprasCode, daysDiff, isOverdue)

	if len(ret) == 0 {
		panic("no return value specified for SendInspectionReminder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, int, bool) error); ok {
		r0 = rf(ctx, userID, scheduleID, sarprasCode, daysDiff, isOverdue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendRefillReminder provides a mock function with given fields: ctx, sarprasID, inspectionID, sarprasCode, sarprasName
func (_m *NotificationService) SendRefillReminder(ctx context.Context, sarprasID uint, inspectionID uint, sarprasCode string, sarprasName string) error {
	ret := _m.Called(ctx, sarprasID, inspectionID, sarprasCode, sarprasName)

	if len(ret) == 0 {
		panic("no return value specified for SendRefillReminder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, string) error); ok {
		r0 = rf(ctx, sarprasID, inspectionID, sarprasCode, sarprasName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
