// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RefillRepository is an autogenerated mock type for the RefillRepository type
type RefillRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: order, items
func (_m *RefillRepository) CreateOrder(order *domain.RefillOrder, items []domain.RefillOrderItem) error {
	ret := _m.Called(order, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.RefillOrder, []domain.RefillOrderItem) error); ok {
		r0 = rf(order, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveRefillBySarprasID provides a mock function with given fields: ctx, sarprasID
func (_m *RefillRepository) GetActiveRefillBySarprasID(ctx context.Context, sarprasID uint) (*domain.RefillStatus, error) {
	ret := _m.Called(ctx, sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveRefillBySarprasID")
	}

	var r0 *domain.RefillStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.RefillStatus, error)); ok {
		return rf(ctx, sarprasID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.RefillStatus); ok {
		r0 = rf(ctx, sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefillStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAparDetail provides a mock function with given fields: sarprasID
func (_m *RefillRepository) GetAparDetail(sarprasID uint) (*domain.AparListRow, error) {
	ret := _m.Called(sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetAparDetail")
	}

	var r0 *domain.AparListRow
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.AparListRow, error)); ok {
		return rf(sarprasID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.AparListRow); ok {
		r0 = rf(sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AparListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAparList provides a mock function with given fields: params
func (_m *RefillRepository) GetAparList(params domain.GetAparListParams) ([]domain.AparListRow, int, int, int, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetAparList")
	}

	var r0 []domain.AparListRow
	var r1 int
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(domain.GetAparListParams) ([]domain.AparListRow, int, int, int, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain.GetAparListParams) []domain.AparListRow); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AparListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.GetAparListParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(domain.GetAparListParams) int); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(domain.GetAparListParams) int); ok {
		r3 = rf(params)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(domain.GetAparListParams) error); ok {
		r4 = rf(params)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// GetAparsNearExpiry provides a mock function with given fields: daysAhead
func (_m *RefillRepository) GetAparsNearExpiry(daysAhead int) ([]domain.AparNearExpiry, error) {
	ret := _m.Called(daysAhead)

	if len(ret) == 0 {
		panic("no return value specified for GetAparsNearExpiry")
	}

	var r0 []domain.AparNearExpiry
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.AparNearExpiry, error)); ok {
		return rf(daysAhead)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.AparNearExpiry); ok {
		r0 = rf(daysAhead)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AparNearExpiry)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(daysAhead)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmailsByDepartment provides a mock function with given fields: deptName
func (_m *RefillRepository) GetEmailsByDepartment(deptName string) ([]string, error) {
	ret := _m.Called(deptName)

	if len(ret) == 0 {
		panic("no return value specified for GetEmailsByDepartment")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(deptName)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(deptName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(deptName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmailsByRole provides a mock function with given fields: role
func (_m *RefillRepository) GetEmailsByRole(role string) ([]string, error) {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for GetEmailsByRole")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(role)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVerifyDetail provides a mock function with given fields: sarprasID
func (_m *RefillRepository) GetVerifyDetail(sarprasID uint) (*domain.VerifyDetailResponse, error) {
	ret := _m.Called(sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifyDetail")
	}

	var r0 *domain.VerifyDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.VerifyDetailResponse, error)); ok {
		return rf(sarprasID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.VerifyDetailResponse); ok {
		r0 = rf(sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VerifyDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateItemEvidence provides a mock function with given fields: itemID, userID, newDate, path, reason
func (_m *RefillRepository) UpdateItemEvidence(itemID uint, userID uint, newDate time.Time, path string, reason string) error {
	ret := _m.Called(itemID, userID, newDate, path, reason)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItemEvidence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, time.Time, string, string) error); ok {
		r0 = rf(itemID, userID, newDate, path, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateSarprasForMarkUsed provides a mock function with given fields: sarprasIDs
func (_m *RefillRepository) ValidateSarprasForMarkUsed(sarprasIDs []uint) ([]uint, error) {
	ret := _m.Called(sarprasIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSarprasForMarkUsed")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func([]uint) ([]uint, error)); ok {
		return rf(sarprasIDs)
	}
	if rf, ok := ret.Get(0).(func([]uint) []uint); ok {
		r0 = rf(sarprasIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func([]uint) error); ok {
		r1 = rf(sarprasIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateSarprasForRefill provides a mock function with given fields: sarprasIDs
func (_m *RefillRepository) ValidateSarprasForRefill(sarprasIDs []uint) ([]uint, error) {
	ret := _m.Called(sarprasIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSarprasForRefill")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func([]uint) ([]uint, error)); ok {
		return rf(sarprasIDs)
	}
	if rf, ok := ret.Get(0).(func([]uint) []uint); ok {
		r0 = rf(sarprasIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func([]uint) error); ok {
		r1 = rf(sarprasIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefillRepository creates a new instance of RefillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefillRepository {
	mock := &RefillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
