// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RefillService is an autogenerated mock type for the RefillService type
type RefillService struct {
	mock.Mock
}

// GetAparDetail provides a mock function with given fields: sarprasID
func (_m *RefillService) GetAparDetail(sarprasID uint) (*domain.AparListRow, error) {
	ret := _m.Called(sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetAparDetail")
	}

	var r0 *domain.AparListRow
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.AparListRow, error)); ok {
		return rf(sarprasID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.AparListRow); ok {
		r0 = rf(sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AparListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVerifyDetail provides a mock function with given fields: itemID
func (_m *RefillService) GetVerifyDetail(itemID uint) (*domain.VerifyDetailResponse, error) {
	ret := _m.Called(itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifyDetail")
	}

	var r0 *domain.VerifyDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.VerifyDetailResponse, error)); ok {
		return rf(itemID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.VerifyDetailResponse); ok {
		r0 = rf(itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VerifyDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListApar provides a mock function with given fields: params
func (_m *RefillService) ListApar(params domain.GetAparListParams) ([]domain.AparListRow, int, int, int, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for ListApar")
	}

	var r0 []domain.AparListRow
	var r1 int
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(domain.GetAparListParams) ([]domain.AparListRow, int, int, int, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain.GetAparListParams) []domain.AparListRow); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AparListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.GetAparListParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(domain.GetAparListParams) int); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(domain.GetAparListParams) int); ok {
		r3 = rf(params)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(domain.GetAparListParams) error); ok {
		r4 = rf(params)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MarkAsUsed provides a mock function with given fields: req, markedBy
func (_m *RefillService) MarkAsUsed(req domain.MarkAsUsedRequest, markedBy uint) error {
	ret := _m.Called(req, markedBy)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.MarkAsUsedRequest, uint) error); ok {
		r0 = rf(req, markedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendExpiryReminders provides a mock function with no fields
func (_m *RefillService) SendExpiryReminders() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendExpiryReminders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitEvidence provides a mock function with given fields: req, evidenceBy
func (_m *RefillService) SubmitEvidence(req domain.SubmitEvidenceRequest, evidenceBy uint) error {
	ret := _m.Called(req, evidenceBy)

	if len(ret) == 0 {
		panic("no return value specified for SubmitEvidence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.SubmitEvidenceRequest, uint) error); ok {
		r0 = rf(req, evidenceBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitPO provides a mock function with given fields: req, submittedBy
func (_m *RefillService) SubmitPO(req domain.SubmitPORequest, submittedBy uint) error {
	ret := _m.Called(req, submittedBy)

	if len(ret) == 0 {
		panic("no return value specified for SubmitPO")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.SubmitPORequest, uint) error); ok {
		r0 = rf(req, submittedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateApar provides a mock function with given fields: sarprasIDs
func (_m *RefillService) ValidateApar(sarprasIDs []uint) ([]uint, error) {
	ret := _m.Called(sarprasIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateApar")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func([]uint) ([]uint, error)); ok {
		return rf(sarprasIDs)
	}
	if rf, ok := ret.Get(0).(func([]uint) []uint); ok {
		r0 = rf(sarprasIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func([]uint) error); ok {
		r1 = rf(sarprasIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyItem provides a mock function with given fields: req, reviewerID
func (_m *RefillService) VerifyItem(req domain.VerifyRefillRequest, reviewerID uint) error {
	ret := _m.Called(req, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for VerifyItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.VerifyRefillRequest, uint) error); ok {
		r0 = rf(req, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefillService creates a new instance of RefillService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefillService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefillService {
	mock := &RefillService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
