// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

// GetSarprasReport provides a mock function with given fields: ctx, deptID, status, scheduleStatus, startDate, endDate
func (_m *ReportRepository) GetSarprasReport(ctx context.Context, deptID string, status string, scheduleStatus string, startDate string, endDate string) ([]domain.ReportSarprasRow, error) {
	ret := _m.Called(ctx, deptID, status, scheduleStatus, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSarprasReport")
	}

	var r0 []domain.ReportSarprasRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) ([]domain.ReportSarprasRow, error)); ok {
		return rf(ctx, deptID, status, scheduleStatus, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) []domain.ReportSarprasRow); ok {
		r0 = rf(ctx, deptID, status, scheduleStatus, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReportSarprasRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, deptID, status, scheduleStatus, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
