// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReviewService is an autogenerated mock type for the ReviewService type
type ReviewService struct {
	mock.Mock
}

// CancelClaimReview provides a mock function with given fields: ctx, repairOrderID, reviewerID
func (_m *ReviewService) CancelClaimReview(ctx context.Context, repairOrderID uint, reviewerID uint) error {
	ret := _m.Called(ctx, repairOrderID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for CancelClaimReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, repairOrderID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimReview provides a mock function with given fields: ctx, repairOrderID, reviewerID
func (_m *ReviewService) ClaimReview(ctx context.Context, repairOrderID uint, reviewerID uint) error {
	ret := _m.Called(ctx, repairOrderID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, repairOrderID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHistoryDetail provides a mock function with given fields: ctx, reviewID
func (_m *ReviewService) GetHistoryDetail(ctx context.Context, reviewID uint) (*domain.ReviewHistoryDetail, error) {
	ret := _m.Called(ctx, reviewID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryDetail")
	}

	var r0 *domain.ReviewHistoryDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.ReviewHistoryDetail, error)); ok {
		return rf(ctx, reviewID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.ReviewHistoryDetail); ok {
		r0 = rf(ctx, reviewID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReviewHistoryDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, reviewID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewDetail provides a mock function with given fields: ctx, repairOrderID
func (_m *ReviewService) GetReviewDetail(ctx context.Context, repairOrderID uint) (*domain.ReviewDetailResponse, error) {
	ret := _m.Called(ctx, repairOrderID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewDetail")
	}

	var r0 *domain.ReviewDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.ReviewDetailResponse, error)); ok {
		return rf(ctx, repairOrderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.ReviewDetailResponse); ok {
		r0 = rf(ctx, repairOrderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReviewDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, repairOrderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewHistory provides a mock function with given fields: ctx, repairOrderID
func (_m *ReviewService) GetReviewHistory(ctx context.Context, repairOrderID uint) ([]domain.ReviewOrder, error) {
	ret := _m.Called(ctx, repairOrderID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewHistory")
	}

	var r0 []domain.ReviewOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.ReviewOrder, error)); ok {
		return rf(ctx, repairOrderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.ReviewOrder); ok {
		r0 = rf(ctx, repairOrderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReviewOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, repairOrderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewSummary provides a mock function with given fields: ctx
func (_m *ReviewService) GetReviewSummary(ctx context.Context) (*domain.ReviewSummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewSummary")
	}

	var r0 *domain.ReviewSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.ReviewSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.ReviewSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReviewSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPendingReviews provides a mock function with given fields: ctx, filter
func (_m *ReviewService) ListPendingReviews(ctx context.Context, filter domain.ReviewFilter) ([]domain.ReviewRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingReviews")
	}

	var r0 []domain.ReviewRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ReviewFilter) ([]domain.ReviewRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ReviewFilter) []domain.ReviewRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReviewRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ReviewFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ReviewFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListQSHistory provides a mock function with given fields: ctx, reviewerID, filter
func (_m *ReviewService) ListQSHistory(ctx context.Context, reviewerID uint, filter domain.ReviewHistoryFilter) ([]domain.ReviewHistoryRow, int64, error) {
	ret := _m.Called(ctx, reviewerID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListQSHistory")
	}

	var r0 []domain.ReviewHistoryRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ReviewHistoryFilter) ([]domain.ReviewHistoryRow, int64, error)); ok {
		return rf(ctx, reviewerID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ReviewHistoryFilter) []domain.ReviewHistoryRow); ok {
		r0 = rf(ctx, reviewerID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReviewHistoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, domain.ReviewHistoryFilter) int64); ok {
		r1 = rf(ctx, reviewerID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, domain.ReviewHistoryFilter) error); ok {
		r2 = rf(ctx, reviewerID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListReviewsByRepairOrderID provides a mock function with given fields: ctx, repairOrderID, limit, offset
func (_m *ReviewService) ListReviewsByRepairOrderID(ctx context.Context, repairOrderID uint, limit int, offset int) ([]domain.ReviewOrder, int64, error) {
	ret := _m.Called(ctx, repairOrderID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListReviewsByRepairOrderID")
	}

	var r0 []domain.ReviewOrder
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) ([]domain.ReviewOrder, int64, error)); ok {
		return rf(ctx, repairOrderID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int, int) []domain.ReviewOrder); ok {
		r0 = rf(ctx, repairOrderID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReviewOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int, int) int64); ok {
		r1 = rf(ctx, repairOrderID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, int, int) error); ok {
		r2 = rf(ctx, repairOrderID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SubmitReview provides a mock function with given fields: ctx, repairOrderID, reviewerID, req
func (_m *ReviewService) SubmitReview(ctx context.Context, repairOrderID uint, reviewerID uint, req domain.ReviewSubmitRequest) error {
	ret := _m.Called(ctx, repairOrderID, reviewerID, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, domain.ReviewSubmitRequest) error); ok {
		r0 = rf(ctx, repairOrderID, reviewerID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReviewService creates a new instance of ReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewService {
	mock := &ReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
