// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// SarprasService is an autogenerated mock type for the SarprasService type
type SarprasService struct {
	mock.Mock
}

// BulkImportParse provides a mock function with given fields: ctx, file, header
func (_m *SarprasService) BulkImportParse(ctx context.Context, file multipart.File, header *multipart.FileHeader) (*domain.BulkParseResponse, error) {
	ret := _m.Called(ctx, file, header)

	if len(ret) == 0 {
		panic("no return value specified for BulkImportParse")
	}

	var r0 *domain.BulkParseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, *multipart.FileHeader) (*domain.BulkParseResponse, error)); ok {
		return rf(ctx, file, header)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multipart.File, *multipart.FileHeader) *domain.BulkParseResponse); ok {
		r0 = rf(ctx, file, header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BulkParseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, multipart.File, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, file, header)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BulkImportValidate provides a mock function with given fields: ctx, req
func (_m *SarprasService) BulkImportValidate(ctx context.Context, req domain.BulkExecuteRequest) (*domain.BulkValidateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for BulkImportValidate")
	}

	var r0 *domain.BulkValidateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BulkExecuteRequest) (*domain.BulkValidateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BulkExecuteRequest) *domain.BulkValidateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BulkValidateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BulkExecuteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckEligibility provides a mock function with given fields: ctx, userID, code
func (_m *SarprasService) CheckEligibility(ctx context.Context, userID uint, code string) (*domain.CheckerEligibility, error) {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for CheckEligibility")
	}

	var r0 *domain.CheckerEligibility
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) (*domain.CheckerEligibility, error)); ok {
		return rf(ctx, userID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) *domain.CheckerEligibility); ok {
		r0 = rf(ctx, userID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CheckerEligibility)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, userID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteBulkImportInTx provides a mock function with given fields: ctx, tx, items, userID
func (_m *SarprasService) ExecuteBulkImportInTx(ctx context.Context, tx *gorm.DB, items []domain.BulkImportItemRequest, userID uint) (int, error) {
	ret := _m.Called(ctx, tx, items, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteBulkImportInTx")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []domain.BulkImportItemRequest, uint) (int, error)); ok {
		return rf(ctx, tx, items, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []domain.BulkImportItemRequest, uint) int); ok {
		r0 = rf(ctx, tx, items, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, []domain.BulkImportItemRequest, uint) error); ok {
		r1 = rf(ctx, tx, items, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExportPDF provides a mock function with given fields: ctx, userID, req
func (_m *SarprasService) ExportPDF(ctx context.Context, userID uint, req domain.ExportSarprasPDFRequest) ([]byte, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ExportPDF")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ExportSarprasPDFRequest) ([]byte, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ExportSarprasPDFRequest) []byte); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, domain.ExportSarprasPDFRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateQRCode provides a mock function with given fields: ctx, sarprasID
func (_m *SarprasService) GenerateQRCode(ctx context.Context, sarprasID uint) ([]byte, error) {
	ret := _m.Called(ctx, sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQRCode")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]byte, error)); ok {
		return rf(ctx, sarprasID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []byte); ok {
		r0 = rf(ctx, sarprasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByQRCode provides a mock function with given fields: ctx, code
func (_m *SarprasService) GetByQRCode(ctx context.Context, code string) (*domain.Sarpras, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByQRCode")
	}

	var r0 *domain.Sarpras
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Sarpras, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Sarpras); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sarpras)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSarpras provides a mock function with given fields: ctx, id
func (_m *SarprasService) GetSarpras(ctx context.Context, id uint) (*domain.Sarpras, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSarpras")
	}

	var r0 *domain.Sarpras
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Sarpras, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Sarpras); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sarpras)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSarprasDetail provides a mock function with given fields: ctx, code
func (_m *SarprasService) GetSarprasDetail(ctx context.Context, code string) (*domain.SarprasDetailResponse, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetSarprasDetail")
	}

	var r0 *domain.SarprasDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.SarprasDetailResponse, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.SarprasDetailResponse); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SarprasDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSarprasTypeDetail provides a mock function with given fields: ctx, id
func (_m *SarprasService) GetSarprasTypeDetail(ctx context.Context, id uint) (*domain.SarprasTypeDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSarprasTypeDetail")
	}

	var r0 *domain.SarprasTypeDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.SarprasTypeDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.SarprasTypeDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SarprasTypeDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateMetadata provides a mock function with given fields: ctx
func (_m *SarprasService) GetTemplateMetadata(ctx context.Context) ([]domain.SarprasTypeRow, []domain.DepartmentRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateMetadata")
	}

	var r0 []domain.SarprasTypeRow
	var r1 []domain.DepartmentRow
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SarprasTypeRow, []domain.DepartmentRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SarprasTypeRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasTypeRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []domain.DepartmentRow); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.DepartmentRow)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListSarpras provides a mock function with given fields: ctx, filter
func (_m *SarprasService) ListSarpras(ctx context.Context, filter domain.SarprasFilter) ([]domain.SarprasRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSarpras")
	}

	var r0 []domain.SarprasRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SarprasFilter) ([]domain.SarprasRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SarprasFilter) []domain.SarprasRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SarprasFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.SarprasFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListSarprasTypes provides a mock function with given fields: ctx, filter
func (_m *SarprasService) ListSarprasTypes(ctx context.Context, filter map[string]interface{}) ([]domain.SarprasTypeRow, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSarprasTypes")
	}

	var r0 []domain.SarprasTypeRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]domain.SarprasTypeRow, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []domain.SarprasTypeRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasTypeRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestCreateSarpras provides a mock function with given fields: ctx, userID, req, notes
func (_m *SarprasService) RequestCreateSarpras(ctx context.Context, userID uint, req *domain.Sarpras, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, req, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestCreateSarpras")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Sarpras, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, req, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Sarpras, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, req, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *domain.Sarpras, string) error); ok {
		r1 = rf(ctx, userID, req, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestCreateSarprasImport provides a mock function with given fields: ctx, userID, req, notes
func (_m *SarprasService) RequestCreateSarprasImport(ctx context.Context, userID uint, req domain.BulkExecuteRequest, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, req, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestCreateSarprasImport")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.BulkExecuteRequest, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, req, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.BulkExecuteRequest, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, req, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, domain.BulkExecuteRequest, string) error); ok {
		r1 = rf(ctx, userID, req, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestCreateSarprasType provides a mock function with given fields: ctx, userID, req, notes
func (_m *SarprasService) RequestCreateSarprasType(ctx context.Context, userID uint, req *domain.SarprasType, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, req, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestCreateSarprasType")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.SarprasType, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, req, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.SarprasType, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, req, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *domain.SarprasType, string) error); ok {
		r1 = rf(ctx, userID, req, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestDeleteSarpras provides a mock function with given fields: ctx, userID, id, notes
func (_m *SarprasService) RequestDeleteSarpras(ctx context.Context, userID uint, id uint, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, id, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeleteSarpras")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, id, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, id, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, userID, id, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestDeleteSarprasType provides a mock function with given fields: ctx, userID, id, notes
func (_m *SarprasService) RequestDeleteSarprasType(ctx context.Context, userID uint, id uint, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, id, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestDeleteSarprasType")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, id, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, id, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, userID, id, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestEditSarpras provides a mock function with given fields: ctx, userID, id, req, notes
func (_m *SarprasService) RequestEditSarpras(ctx context.Context, userID uint, id uint, req *domain.Sarpras, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, id, req, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestEditSarpras")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.Sarpras, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, id, req, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.Sarpras, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, id, req, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *domain.Sarpras, string) error); ok {
		r1 = rf(ctx, userID, id, req, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestEditSarprasType provides a mock function with given fields: ctx, userID, id, req, notes
func (_m *SarprasService) RequestEditSarprasType(ctx context.Context, userID uint, id uint, req *domain.SarprasType, notes string) (*domain.ApprovalResponse, error) {
	ret := _m.Called(ctx, userID, id, req, notes)

	if len(ret) == 0 {
		panic("no return value specified for RequestEditSarprasType")
	}

	var r0 *domain.ApprovalResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.SarprasType, string) (*domain.ApprovalResponse, error)); ok {
		return rf(ctx, userID, id, req, notes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.SarprasType, string) *domain.ApprovalResponse); ok {
		r0 = rf(ctx, userID, id, req, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *domain.SarprasType, string) error); ok {
		r1 = rf(ctx, userID, id, req, notes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusExpiry provides a mock function with given fields: ctx
func (_m *SarprasService) UpdateStatusExpiry(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusExpiry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSarprasService creates a new instance of SarprasService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSarprasService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SarprasService {
	mock := &SarprasService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
