// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// SarprasTypeRepository is an autogenerated mock type for the SarprasTypeRepository type
type SarprasTypeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, st
func (_m *SarprasTypeRepository) Create(ctx context.Context, st *domain.SarprasType) error {
	ret := _m.Called(ctx, st)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SarprasType) error); ok {
		r0 = rf(ctx, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateParameter provides a mock function with given fields: ctx, p
func (_m *SarprasTypeRepository) CreateParameter(ctx context.Context, p *domain.Parameter) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateParameter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Parameter) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTx provides a mock function with given fields: tx, st
func (_m *SarprasTypeRepository) CreateTx(tx *gorm.DB, st *domain.SarprasType) error {
	ret := _m.Called(tx, st)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *domain.SarprasType) error); ok {
		r0 = rf(tx, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SarprasTypeRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteParameter provides a mock function with given fields: ctx, id
func (_m *SarprasTypeRepository) DeleteParameter(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParameter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTx provides a mock function with given fields: tx, id
func (_m *SarprasTypeRepository) DeleteTx(tx *gorm.DB, id uint) error {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Detail provides a mock function with given fields: ctx, id
func (_m *SarprasTypeRepository) Detail(ctx context.Context, id uint) (*domain.SarprasTypeDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Detail")
	}

	var r0 *domain.SarprasTypeDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.SarprasTypeDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.SarprasTypeDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SarprasTypeDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *SarprasTypeRepository) FindByCode(ctx context.Context, code string) (*domain.SarprasType, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *domain.SarprasType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.SarprasType, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.SarprasType); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SarprasType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *SarprasTypeRepository) FindByID(ctx context.Context, id uint) (*domain.SarprasType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.SarprasType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.SarprasType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.SarprasType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SarprasType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExistingIDs provides a mock function with given fields: ctx, ids
func (_m *SarprasTypeRepository) FindExistingIDs(ctx context.Context, ids []uint) ([]uint, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindExistingIDs")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]uint, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []uint); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExpiryParamID provides a mock function with given fields: ctx, typeID
func (_m *SarprasTypeRepository) FindExpiryParamID(ctx context.Context, typeID uint) (*uint, error) {
	ret := _m.Called(ctx, typeID)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiryParamID")
	}

	var r0 *uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*uint, error)); ok {
		return rf(ctx, typeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *uint); ok {
		r0 = rf(ctx, typeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, typeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParametersByType provides a mock function with given fields: ctx, typeID
func (_m *SarprasTypeRepository) GetParametersByType(ctx context.Context, typeID uint) ([]domain.Parameter, error) {
	ret := _m.Called(ctx, typeID)

	if len(ret) == 0 {
		panic("no return value specified for GetParametersByType")
	}

	var r0 []domain.Parameter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Parameter, error)); ok {
		return rf(ctx, typeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Parameter); ok {
		r0 = rf(ctx, typeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Parameter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, typeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *SarprasTypeRepository) List(ctx context.Context, filter map[string]interface{}) ([]domain.SarprasTypeRow, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.SarprasTypeRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]domain.SarprasTypeRow, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []domain.SarprasTypeRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasTypeRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, st
func (_m *SarprasTypeRepository) Update(ctx context.Context, st *domain.SarprasType) error {
	ret := _m.Called(ctx, st)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SarprasType) error); ok {
		r0 = rf(ctx, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateParameter provides a mock function with given fields: ctx, p
func (_m *SarprasTypeRepository) UpdateParameter(ctx context.Context, p *domain.Parameter) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParameter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Parameter) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWithParamsTx provides a mock function with given fields: tx, id, st
func (_m *SarprasTypeRepository) UpdateWithParamsTx(tx *gorm.DB, id uint, st *domain.SarprasType) error {
	ret := _m.Called(tx, id, st)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithParamsTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, *domain.SarprasType) error); ok {
		r0 = rf(tx, id, st)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSarprasTypeRepository creates a new instance of SarprasTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSarprasTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SarprasTypeRepository {
	mock := &SarprasTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
