// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SarprasRepository is an autogenerated mock type for the SarprasRepository type
type SarprasRepository struct {
	mock.Mock
}

// CountByTypeAndDepts provides a mock function with given fields: ctx, typeID, locationDeptID, picDeptID
func (_m *SarprasRepository) CountByTypeAndDepts(ctx context.Context, typeID uint, locationDeptID uint, picDeptID uint) (int, error) {
	ret := _m.Called(ctx, typeID, locationDeptID, picDeptID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTypeAndDepts")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint) (int, error)); ok {
		return rf(ctx, typeID, locationDeptID, picDeptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint) int); ok {
		r0 = rf(ctx, typeID, locationDeptID, picDeptID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, uint) error); ok {
		r1 = rf(ctx, typeID, locationDeptID, picDeptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTx provides a mock function with given fields: tx, s
func (_m *SarprasRepository) CreateTx(tx *gorm.DB, s *domain.Sarpras) error {
	ret := _m.Called(tx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *domain.Sarpras) error); ok {
		r0 = rf(tx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTx provides a mock function with given fields: tx, id
func (_m *SarprasRepository) DeleteTx(tx *gorm.DB, id uint) error {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *SarprasRepository) FindByCode(ctx context.Context, code string) (*domain.Sarpras, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *domain.Sarpras
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Sarpras, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Sarpras); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sarpras)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *SarprasRepository) FindByID(ctx context.Context, id uint) (*domain.Sarpras, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Sarpras
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Sarpras, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Sarpras); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sarpras)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindEligibleChecker provides a mock function with given fields: tx, typeID, deptID
func (_m *SarprasRepository) FindEligibleChecker(tx *gorm.DB, typeID uint, deptID uint) (uint, error) {
	ret := _m.Called(tx, typeID, deptID)

	if len(ret) == 0 {
		panic("no return value specified for FindEligibleChecker")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint) (uint, error)); ok {
		return rf(tx, typeID, deptID)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint) uint); ok {
		r0 = rf(tx, typeID, deptID)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, uint) error); ok {
		r1 = rf(tx, typeID, deptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckerAssignedSarpras provides a mock function with given fields: ctx, userID, filter
func (_m *SarprasRepository) GetCheckerAssignedSarpras(ctx context.Context, userID uint, filter domain.SarprasFilter) ([]domain.SarprasRow, int64, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckerAssignedSarpras")
	}

	var r0 []domain.SarprasRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.SarprasFilter) ([]domain.SarprasRow, int64, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.SarprasFilter) []domain.SarprasRow); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, domain.SarprasFilter) int64); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, domain.SarprasFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetExpiringAPAR provides a mock function with given fields: ctx, before
func (_m *SarprasRepository) GetExpiringAPAR(ctx context.Context, before time.Time) ([]domain.SarprasRow, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringAPAR")
	}

	var r0 []domain.SarprasRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.SarprasRow, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.SarprasRow); ok {
		r0 = rf(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastChecker provides a mock function with given fields: ctx, sarprasID
func (_m *SarprasRepository) GetLastChecker(ctx context.Context, sarprasID uint) (string, error) {
	ret := _m.Called(ctx, sarprasID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastChecker")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (string, error)); ok {
		return rf(ctx, sarprasID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = rf(ctx, sarprasID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, sarprasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestCodeTx provides a mock function with given fields: tx, typeID, locationDeptID
func (_m *SarprasRepository) GetLatestCodeTx(tx *gorm.DB, typeID uint, locationDeptID uint) (string, error) {
	ret := _m.Called(tx, typeID, locationDeptID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCodeTx")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint) (string, error)); ok {
		return rf(tx, typeID, locationDeptID)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, uint) string); ok {
		r0 = rf(tx, typeID, locationDeptID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, uint) error); ok {
		r1 = rf(tx, typeID, locationDeptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *SarprasRepository) List(ctx context.Context, filter domain.SarprasFilter) ([]domain.SarprasRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.SarprasRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SarprasFilter) ([]domain.SarprasRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SarprasFilter) []domain.SarprasRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SarprasRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SarprasFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.SarprasFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *SarprasRepository) UpdateStatus(ctx context.Context, id uint, status domain.SarprasStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.SarprasStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByExpiry provides a mock function with given fields: ctx
func (_m *SarprasRepository) UpdateStatusByExpiry(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByExpiry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTx provides a mock function with given fields: tx, id, s
func (_m *SarprasRepository) UpdateTx(tx *gorm.DB, id uint, s *domain.Sarpras) error {
	ret := _m.Called(tx, id, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, *domain.Sarpras) error); ok {
		r0 = rf(tx, id, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSarprasRepository creates a new instance of SarprasRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSarprasRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SarprasRepository {
	mock := &SarprasRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
