// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "emertrack/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, userID, oldPassword, newPassword
func (_m *UserService) ChangePassword(ctx context.Context, userID uint, oldPassword string, newPassword string) error {
	ret := _m.Called(ctx, userID, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, userID, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, actorID, user, roles, sarprasTypeIDs
func (_m *UserService) CreateUser(ctx context.Context, actorID uint, user *domain.User, roles []domain.Role, sarprasTypeIDs []uint) (*domain.User, error) {
	ret := _m.Called(ctx, actorID, user, roles, sarprasTypeIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.User, []domain.Role, []uint) (*domain.User, error)); ok {
		return rf(ctx, actorID, user, roles, sarprasTypeIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.User, []domain.Role, []uint) *domain.User); ok {
		r0 = rf(ctx, actorID, user, roles, sarprasTypeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *domain.User, []domain.Role, []uint) error); ok {
		r1 = rf(ctx, actorID, user, roles, sarprasTypeIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, actorID, userID
func (_m *UserService) DeleteUser(ctx context.Context, actorID uint, userID uint) error {
	ret := _m.Called(ctx, actorID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, actorID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForceResetPassword provides a mock function with given fields: ctx, userID, newPassword
func (_m *UserService) ForceResetPassword(ctx context.Context, userID uint, newPassword string) error {
	ret := _m.Called(ctx, userID, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ForceResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, userID, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *UserService) GetUser(ctx context.Context, id uint) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserService) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, filter
func (_m *UserService) ListUsers(ctx context.Context, filter domain.UserFilter) ([]domain.UserRow, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []domain.UserRow
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserFilter) ([]domain.UserRow, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserFilter) []domain.UserRow); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateUser provides a mock function with given fields: ctx, actorID, userID, updates, newRoles, newSarprasIDs
func (_m *UserService) UpdateUser(ctx context.Context, actorID uint, userID uint, updates *domain.User, newRoles []domain.Role, newSarprasIDs []uint) (*domain.User, error) {
	ret := _m.Called(ctx, actorID, userID, updates, newRoles, newSarprasIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.User, []domain.Role, []uint) (*domain.User, error)); ok {
		return rf(ctx, actorID, userID, updates, newRoles, newSarprasIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *domain.User, []domain.Role, []uint) *domain.User); ok {
		r0 = rf(ctx, actorID, userID, updates, newRoles, newSarprasIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *domain.User, []domain.Role, []uint) error); ok {
		r1 = rf(ctx, actorID, userID, updates, newRoles, newSarprasIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateLogin provides a mock function with given fields: ctx, email, password
func (_m *UserService) ValidateLogin(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogin")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
