import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BatchTrack System",
  description: "Generated by create next app",
};

/**
 * Root Layout (Tata Letak Utama) Aplikasi NextJS.
 * 
 * **Konsep Arsitektural:**
 * 1. **Pondasi HTML & Body**: Membungkus seluruh aplikasi dengan tag `<html>` dan `<body>`.
 *    Merupakan tempat ideal untuk memuat konfigurasi global seperti font, CSS utama (`globals.css`), 
 *    dan provider context yang dibutuhkan oleh seluruh halaman (termasuk halaman login maupun dashboard).
 * 2. **Server Component Default**: Layout ini berjalan di sisi server (Server-Side) secara default,
 *    sehingga metadata (Title, Description) bisa dirender untuk keperluan SEO/OpenGraph sebelum 
 *    dikirim ke browser klien.
 *
 * @param {React.ReactNode} children - Komponen halaman (`page.tsx`) yang akan disuntikkan ke dalam layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
